version: 2
jobs:
  build:
    docker:
    # Primary container image where all steps run.
     - image: blktivity
    # Secondary container image on common network.
     - image: mongo:2.6.8
       command: [mongod, --smallfiles]


    steps:
      - checkout

      - run:
        name: run unit test

      # We enable Docker Layer Caching here to speed up image building.
      # using docker-compose so I have to use setup_remote_docker https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker
          docker_layer_caching: true

     - run:
        name: Install Docker client
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker run -d --name db company/proprietary-db:1.2.3

     - run:
        name: Install Docker Compose
        command: |


     - run:
        name: Start container and verify it's working
        command: |

     - run:
        name: Build docker push
        command: |


     - deploy:
        name: Build and push Docker image
        command: |
          docker build -t company/app:$CIRCLE_BRANCH .


    - store_artifacts:
